project: 
  type: website
  output-dir: html

website: 
  title: ML4DWISE
  favicon: favicon.ico
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Python
        menu:
        - text: Python Intro
          href: python.html
        - text: py-first
          href: python/first.html
      - text: Artificial Intelligence
        menu:
        - text: AI Intro
          href: ai.html
        - text: ai-first
          href: ai/ai-first.html
      - text: Machine Learning
        menu:
          - text: ML Intro
            href: ml.html
          - text: ml-first
            href: ml/ml-first.html
          - text: Machine Learning Introduction
            href: ml/31_machine_learning_introduction.html

format:
  html:
    theme: 
      light: simplex
    css: styles.css
    toc: true
