project: 
  type: website
  output-dir: website

website: 
  title: ML4DWISE
  favicon: favicon.ico
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Python
        menu:
        - text: Python Intro
          href: 1_python/11_python_intro.html
        - text: py-first
          href: 1_python/first.html
      - text: Artificial Intelligence
        menu:
        - text: AI Intro
          href: 2_ai/21_ai_intro.html
        - text: ai-first
          href: 2_ai/ai-first.html
      - text: Machine Learning
        menu:
          - text: ML Intro
            href: 3_ml/31_ml_intro.html
          - text: ml-first
            href: 3_ml/ml-first.html

format:
  html:
    theme: 
      light: simplex
    css: styles.css
    toc: true
