project: 
  type: website
  output-dir: html

website: 
  title: ml4dwise
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Intro
        href: notebooks/intro.html
      - text: Next
        href: notebooks/next.html

format:
  html:
    theme: united
    css: sytle.css
    toc: true
