project: 
  type: website
  output-dir: html

website: 
  title: ml4dwise
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Python
        menu:
          - text: Introduction to Python
            href: 1_python/11_introduction_to_python.html
      - text: Artificial Intelligence
        menu:
          - text: Artificial Intelligence Introduction
            href: 2_ai/21_artificial_intelligence_introduction.html
      - text: Machine Learning
        menu:
          - text: Machine Learning Introduction
            href: 3_ml/31_machine_learning_introduction.html

format:
  html:
    theme: 
      dark: cyborg
      light: lux
    css: styles.css
    toc: true
