project: 
  type: website
  output-dir: html

website: 
  title: ML4DWISE
  favicon: favicon.ico
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Python
        href: python.html
      - text: Artificial Intelligence
        href: ai.html
      - text: Machine Learning
        menu:
          - text: Machine Learning Introduction
            href: ml/31_machine_learning_introduction.html

format:
  html:
    theme: 
      light: simplex
    css: styles.css
    toc: true
